### ISSUE TITLE
Epic - Create Listing

### ISSUE THREAD

**Issue by Parsa-Rajabi** [rachellegelden/Home-Together-Canada#433]
- [x] #434 
- [x] #435
- [x] #436
- [ ] #437 -- Moved to Milestone 3
- [x] #438
- [ ] #439 -- Moved to Milestone 3
- [x] #440 
- [x] #448 
- [x] #449 
- [x] #450 
- [x] #451 
- [x] #452 
- [x] #453 
- [x] #454 
- [x] #455 
- [x] #456 
- [ ] #457  -- Moved to Milestone 3
- [x] #458 
- [x] #459 
- [x] #460 
- [x] #461
